# Generated by Django 4.1 on 2024-04-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_delete_coach_team_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='average_score',
        ),
        migrations.RemoveField(
            model_name='player',
            name='number_of_games',
        ),
    ]
