# Generated by Django 4.1 on 2024-04-08 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='round',
            field=models.IntegerField(choices=[(16, '16th-finals'), (8, 'Eighth-finals'), (4, 'Quarterfinals'), (2, 'Semifinals'), (1, 'Final')], default=16),
        ),
    ]
