# Generated by Django 4.1 on 2024-04-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_game_gameplayer_delete_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='team1_score',
        ),
        migrations.RemoveField(
            model_name='game',
            name='team2_score',
        ),
        migrations.AlterField(
            model_name='gameplayer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
