# Generated by Django 4.1 on 2024-04-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_remove_game_team1_score_remove_game_team2_score_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GamePlayer',
        ),
    ]
